<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"患者管理",
                        "menuJump":"列表",
                        "tableName":"huanzhe"
                    }
                ],
                "menu":"患者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医生管理",
                        "menuJump":"列表",
                        "tableName":"yisheng"
                    }
                ],
                "menu":"医生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"病例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"健康日记管理",
                        "menuJump":"列表",
                        "tableName":"jiankangrizhi"
                    }
                ],
                "menu":"健康日记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"手术记录管理",
                        "menuJump":"列表",
                        "tableName":"shoushu"
                    }
                ],
                "menu":"手术记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"护理记录管理",
                        "menuJump":"列表",
                        "tableName":"huli"
                    }
                ],
                "menu":"护理记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"检查记录管理",
                        "menuJump":"列表",
                        "tableName":"jiancha"
                    }
                ],
                "menu":"检查记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医嘱管理",
                        "menuJump":"列表",
                        "tableName":"yizhu"
                    }
                ],
                "menu":"医嘱管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病例类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBingli"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"讯息类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXunxi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"入院类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryRuyuan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"手术类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShoushu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"护理类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHuli"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"检查类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiancha"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医嘱类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYizhu"
                    }

                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"每日推荐管理",
                        "menuJump":"列表",
                        "tableName":"meirituijian"
                    }
                ],
                "menu":"每日推荐管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医院讯息管理",
                        "menuJump":"列表",
                        "tableName":"xunxi"
                    }
                ],
                "menu":"医院讯息管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"医生管理",
                        "menuJump":"列表",
                        "tableName":"yisheng"
                    }
                ],
                "menu":"医生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"病例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"健康日记管理",
                        "menuJump":"列表",
                        "tableName":"jiankangrizhi"
                    }
                ],
                "menu":"健康日记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"手术记录管理",
                        "menuJump":"列表",
                        "tableName":"shoushu"
                    }
                ],
                "menu":"手术记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"护理记录管理",
                        "menuJump":"列表",
                        "tableName":"huli"
                    }
                ],
                "menu":"护理记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"检查记录管理",
                        "menuJump":"列表",
                        "tableName":"jiancha"
                    }
                ],
                "menu":"检查记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"医嘱管理",
                        "menuJump":"列表",
                        "tableName":"yizhu"
                    }
                ],
                "menu":"医嘱管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"每日推荐管理",
                        "menuJump":"列表",
                        "tableName":"meirituijian"
                    }
                ],
                "menu":"每日推荐管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"医院讯息管理",
                        "menuJump":"列表",
                        "tableName":"xunxi"
                    }
                ],
                "menu":"医院讯息管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"患者",
        "tableName":"huanzhe"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"患者管理",
                        "menuJump":"列表",
                        "tableName":"huanzhe"
                    }
                ],
                "menu":"患者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"病例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"健康日记管理",
                        "menuJump":"列表",
                        "tableName":"jiankangrizhi"
                    }
                ],
                "menu":"健康日记管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"手术记录管理",
                        "menuJump":"列表",
                        "tableName":"shoushu"
                    }
                ],
                "menu":"手术记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"护理记录管理",
                        "menuJump":"列表",
                        "tableName":"huli"
                    }
                ],
                "menu":"护理记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"检查记录管理",
                        "menuJump":"列表",
                        "tableName":"jiancha"
                    }
                ],
                "menu":"检查记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医嘱管理",
                        "menuJump":"列表",
                        "tableName":"yizhu"
                    }
                ],
                "menu":"医嘱管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"每日推荐管理",
                        "menuJump":"列表",
                        "tableName":"meirituijian"
                    }
                ],
                "menu":"每日推荐管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"医院讯息管理",
                        "menuJump":"列表",
                        "tableName":"xunxi"
                    }
                ],
                "menu":"医院讯息管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"医生",
        "tableName":"yisheng"
    }
];

var hasMessage = '';
